Process started (PID=2236) >>>
ic| fr_video_controls.py:52 in clickFunction() at 14:17:11.756
ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: <fr_video_controls.ImageButton object .!mainframe.!videocontrolsframe.!imagebutton5>
ic| fr_video_canvas.py:81 in show_next_frame()- self.frame_num: 1
ic| fr_video_controls.py:179 in play_pause_callback()
    self.play_button: <fr_video_controls.ImageButton object .!mainframe.!videocontrolsframe.!imagebutton5>
	 
ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:81 in show_next_frame()- self.frame_num: 2

ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:81 in show_next_frame()- self.frame_num: 3

ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:81 in show_next_frame()- self.frame_num: 4

ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:81 in show_next_frame()- self.frame_num: 5

ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:81 in show_next_frame()- self.frame_num: 6

ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:81 in show_next_frame()- self.frame_num: 7

ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:75 in show_next_frame()- 'end of images'

ic| fr_video_canvas.py:65 in show_next_frame()
    event: None
    button: None
ic| fr_video_canvas.py:104 in show_next_frame() at 14:17:12.155

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\ron\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ron\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "D:\Documents\Programming\PythonCode\tkinter\animators_pal\fr_video_canvas.py", line 79, in show_next_frame
    button.clickFunction()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'clickFunction'